### PR TITLE
feat: add getting started documentation

### PR DESCRIPTION
**Pull request by rpignolet**

### CODE REVIEW

**Comment by wdavidw** [comment]
Could we import the code from this PR directly to [tdp-website](https://github.com/TOSIT-IO/tdp-website) ?

**Comment by rpignolet** [comment]
Yes we will put this documentation in the website but more work need to be done first. This actual documentation is only a draft, this PR is here to show a first version.

**Comment by PaulFarault** [comment]
Notes:

- `cloudalchemy.grafana` role doesn't seem to be available anymore.
- Ansible doesn't seem to be able to parse the inventory (I'm using the sample ones provided in the collections).

**Comment by rpignolet** [comment]
Replaced by https://github.com/TOSIT-IO/tdp-website/pull/65

**Pull request closed without merging**
